# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: jCanvas
tagline: jQuery meets the HTML5 canvas
email: caleb@calebevans.me
description: > # this means to ignore newlines until "baseurl:"
  A jQuery plugin that makes the HTML5 canvas easy to work with. Features include layers, events, drag-and-drop, animation, and much more.
baseurl: "/jcanvas" # the subpath of your site, e.g. /blog
url: "http://projects.calebevans.me/jcanvas" # the base hostname & protocol for your site, e.g. http://example.com

# Serve settings
host: 0.0.0.0 # Enables local site to be accessed from other devices on network

# Google tokens
google_analytics: UA-32407194-1
google_adsense_client_id: ca-pub-6730292125551254

# Build settings
markdown: kramdown
incremental: true
kramdown:
  auto_id_stripping: true
  transliterated_header_ids: true
include:
  - _pages
gems:
  - jekyll-seo-tag
  - jekyll-sitemap
  - stringex
exclude:
  - Gemfile
  - Gemfile.lock

# Collections used for new content types
collections:
  # Core documentation
  core_docs:
    output: true
    permalink: /docs/:path/
  # Plugin documentation
  plugin_docs:
    output: true
    permalink: /plugins/:path/
  # Sites and apps in jCanvas gallery
  gallery_entries:
    output: false

# Set defaults for YAML Front Matter variables
defaults:
  -
    # Use the core_docs layout for all doc sections by default
    scope:
      path: ''
      type: core_docs
    values:
      layout: docs
  -
    # Use the plugin_docs layout for all plugin doc sections by default
    scope:
      path: ''
      type: plugin_docs
    values:
      layout: docs
